theme: minima
title: Welcome to my Portfolio!
author: clnelson
email: cory.nelson@my.strayer.edu
description: > # this means to ignore newlines until "baseurl:"
  This is where I'll showcase projects that I complete and host
  my resume and credentials through the completion of my degree
  program and the successful acquisition of my first developer job.

# social links
twitter_username: cl_nelson4 # DO NOT include the @ character, or else the build will fail!
github_username:  clnelson # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
